### ISSUE TITLE
Create "add new diary" feature

### ISSUE THREAD

**Issue by Sepehrworklife** [Sepehrworklife/diary-book#3]
Hello @sarinaodr 
I hope you will be great.
Please Add the "New Diary" feature to the app.
The following list should be done this week:
1. Create a diary model with the following columns:
    - id(int, primary_key)
    - user_id -> it should be relational with the user's table id column.
    - title(varchar, 255)
    - content(text)
    - date(DateTime)
    - created_datetime(DateTime)
    - **Every column is necessary**
2. Create a form with the above data except for the "created_datetime".
3. Add form to the HTML.
after you have done all of this please report me to go further.
Thanks in advance.

**Comment by Sepehrworklife** [comment]
Please attend to me when you create the table so I can do my work for the "Diary List".

**Comment by sarinaodr** [comment]
hello @Sepehrworklife 
I hope you will be great.
i created the models and forms if they have any problems tell me to fix them 
thank youuuuu :D
